name: "Test old metasrv is compatible with new query; new meta is compatible with old query"
description: "Download old binaries and current binaries, run stateless test with old `meta` and latest `query`"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test
      with:
        path: ./bins/current
        artifacts: sqllogictests,meta,query

    - name: Test compatibility
      shell: bash
      run: |
        bash ./tests/compat/test-compat.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-compat
