name: "Test Enterprise features Standalone"
description: "Running stateless tests in standalone mode"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test

    - name: Minio Setup for (ubuntu-latest only)
      shell: bash
      run: |
        docker run -d --network host --name minio \
                -e "MINIO_ACCESS_KEY=minioadmin" \
                -e "MINIO_SECRET_KEY=minioadmin" \
                -e "MINIO_ADDRESS=:9900" \
                -v /tmp/data:/data \
                -v /tmp/config:/root/.minio \
                minio/minio server /data

        export AWS_ACCESS_KEY_ID=minioadmin
        export AWS_SECRET_ACCESS_KEY=minioadmin
        export AWS_EC2_METADATA_DISABLED=true

        aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://testbucket
        aws --endpoint-url http://127.0.0.1:9900/ s3api put-bucket-versioning --bucket testbucket --versioning-configuration Status=Enabled
        aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data s3://testbucket/admin/data --recursive --no-progress
        aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data/ontime_200.csv s3://testbucket/admin/data/ontime_200_v1.csv --no-progress
        aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data/ontime_200.parquet s3://testbucket/admin/data/ontime_200_v1.parquet --no-progress
        aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data/iceberg s3://testbucket/iceberg_data --recursive --no-progress

    - name: Run Stateful Tests with Standalone mode
      shell: bash
      run: |
        ./scripts/ci/ci-run-ee-tests-standalone-minio.sh
