name: "Benchmark Local"
description: "Run benchmark for local filesystem"
inputs:
  sha:
    description: "commit sha"
    required: true
  run_id:
    description: "benchmark run id"
    required: true
  dataset:
    description: "hits/tpch"
    required: true
  source:
    description: "pr/release"
    required: true
  source_id:
    description: "pr_id/release_tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install script dependencies
      shell: bash
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq python3

    - name: Run Benchmark
      working-directory: benchmark/clickbench
      env:
        BENCHMARK_ID: ${{ inputs.run_id }}
        BENCHMARK_DATASET: ${{ inputs.dataset }}
      shell: bash
      run: |
        ./benchmark_local.sh

    - name: Prepare Metadata
      working-directory: benchmark/clickbench
      shell: bash
      run: |
        case ${{ inputs.source }} in
          pr)
            yq -i '.system = "Databend(PR#${{ inputs.source_id }})"' result.json
            ;;
          release)
            yq -i '.system = "Databend(Release@${{ inputs.source_id }})"' result.json
            ;;
          *)
            echo "Unsupported benchmark source: ${{ inputs.source }}"
            exit 1
        esac
        yq -i '.comment = "commit: ${{ inputs.sha }}"' result.json
        mv result.json result-${{ inputs.dataset }}-local.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-${{ inputs.dataset }}-local
        path: benchmark/clickbench/result-${{ inputs.dataset }}-local.json
