extends: default

ignore: |
  build/
  target/
  .databend/

rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    level: warning
  braces: disable
  brackets: disable
  document-start: disable
  truthy:
    check-keys: false
