name: "Build MacOS"
description: "Build in MacOS"
inputs:
  target:
    description: ""
    required: true
  upload:
    description: "Upload artifact"
    required: false
    default: "true"
  artifacts:
    description: "Artifacts to build"
    required: false
    default: "sqllogictests,meta,query"
runs:
  using: "composite"
  steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Rust setup
      shell: bash
      run: |
        brew unlink python || true
        bash ./scripts/setup/dev_setup.sh -yb
        rustup target add ${{ inputs.target }}

    - name: Cross setup
      if: inputs.target == 'aarch64-apple-darwin'
      shell: bash
      run: |
        echo "JEMALLOC_SYS_WITH_LG_PAGE=14" >> $GITHUB_ENV
        echo "JEMALLOC_SYS_WITH_MALLOC_CONF=oversize_threshold:0,dirty_decay_ms:5000,muzzy_decay_ms:5000" >> $GITHUB_ENV

    - name: Setup build env
      shell: bash
      run: |
        echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Build
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        echo "==> building libs ..."
        cargo -Zgitoxide=fetch -Zgit=shallow-index,shallow-deps build --target ${{ inputs.target }} --profile ${{ env.BUILD_PROFILE }} --lib
        for artifact in ${artifacts//,/ }; do
          echo "==> building databend-$artifact ..."
          cargo -Zgitoxide=fetch -Zgit=shallow-index,shallow-deps build --target ${{ inputs.target }} --profile ${{ env.BUILD_PROFILE }} --bin databend-$artifact
        done

    - name: Upload artifact
      if: inputs.upload == 'true'
      uses: ./.github/actions/artifact_upload
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
