ignore-not-existing: true
output-type: lcov
output-path: ./lcov.info
ignore:
  - "*/lib.rs"
  - "*/bin/*"
  - "*/servers/*"
  - "*/sessions/*"
  - "*/metrics/*"
  - "*/admins/*"
  - "*/target/*"
  - "*/ext/*"
  - "*/exception/*"
  - "*/tests/*"
  - "*/arrow/*"
  - "*/building/*"
  - "*/profiling/*"
  - "*/tracing/*"
  - "*/api/http/debug/*"
  - "*/datasources/example/*"
