name: "Test databend-meta cluster"
description: "Download binaries, setup cluster by joining and leaving"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test

    - name: Test databend-meta cluster
      shell: bash
      run: |
        bash ./tests/meta-cluster/test-meta-cluster.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-meta-cluster
