name: "Benchmark Cloud"
description: "Run benchmark for S3 with cloud storage"
inputs:
  sha:
    description: "commit sha"
    required: true
  run_id:
    description: "benchmark run id"
    required: true
  dataset:
    description: "hits/tpch"
    required: true
  source:
    description: "pr/release"
    required: true
  source_id:
    description: "pr_id/release_tag"
    required: true
  size:
    description: "Small/Medium/Large"
    required: true
  version:
    description: "Databend version"
    required: true
  cloud_user:
    description: "Benchmark cloud user"
    required: true
  cloud_password:
    description: "Benchmark cloud password"
    required: true
  cloud_gateway:
    description: "Benchmark cloud gateway endpoint"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install script dependencies
      shell: bash
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq python3

    - name: Prepare
      working-directory: benchmark/clickbench
      shell: bash
      id: prepare
      env:
        BENDSQL_DSN: "databend://${{ inputs.cloud_user }}:${{ inputs.cloud_password }}@${{ inputs.cloud_gateway }}:443"
      run: |
        if [[ "${{ inputs.dataset }}" == "load" ]]; then
          echo "database=load_test_${{ inputs.run_id }}" >> $GITHUB_OUTPUT
          echo "tries=1" >> $GITHUB_OUTPUT
        else
          echo "database=clickbench" >> $GITHUB_OUTPUT
          echo "tries=3" >> $GITHUB_OUTPUT
        fi

    - name: Run Benchmark
      working-directory: benchmark/clickbench
      env:
        BENCHMARK_ID: ${{ inputs.run_id }}
        BENCHMARK_DATASET: ${{ inputs.dataset }}
        BENCHMARK_SIZE: ${{ inputs.size }}
        BENCHMARK_VERSION: ${{ inputs.version }}
        BENCHMARK_DATABASE: ${{ steps.prepare.outputs.database }}
        BENCHMARK_TRIES: ${{ steps.prepare.outputs.tries }}
        CLOUD_USER: ${{ inputs.cloud_user }}
        CLOUD_PASSWORD: ${{ inputs.cloud_password }}
        CLOUD_GATEWAY: ${{ inputs.cloud_gateway }}
        CLOUD_WAREHOUSE: benchmark-${{ inputs.run_id }}
      shell: bash
      run: |
        ./benchmark_cloud.sh

    - name: Prepare Metadata
      working-directory: benchmark/clickbench
      shell: bash
      run: |
        case ${{ inputs.source }} in
          pr)
            yq -i '.system = "Databend(PR#${{ inputs.source_id }})"' result.json
            ;;
          release)
            yq -i '.system = "Databend(Release@${{ inputs.source_id }})"' result.json
            ;;
          *)
            echo "Unsupported benchmark source: ${{ inputs.source }}"
            exit 1
        esac
        yq -i '.comment = "commit: ${{ inputs.sha }}"' result.json
        mv result.json result-${{ inputs.dataset }}-cloud-${{ inputs.size }}.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-${{ inputs.dataset }}-${{ inputs.size }}
        path: benchmark/clickbench/result-${{ inputs.dataset }}-cloud-${{ inputs.size }}.json

    - name: Remove warehouse
      if: always()
      continue-on-error: true
      shell: bash
      env:
        BENDSQL_DSN: "databend://${{ inputs.cloud_user }}:${{ inputs.cloud_password }}@${{ inputs.cloud_gateway }}:443"
      run: |
        echo "DROP WAREHOUSE IF EXISTS 'benchmark-${{ inputs.run_id }}';" | bendsql
