name: "Test sqllogic Standalone"
description: "Running sqllogic tests in standalone mode"
inputs:
  dirs:
    description: "logic test suites dirs"
    required: true
    default: ""
  handlers:
    description: "logic test handlers, mysql,http,clickhouse"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test
      with:
        artifacts: sqllogictests,meta,query

    - name: Test setup
      shell: bash
      run: |
        bash ./scripts/setup/dev_setup.sh -yd

    - name: Run sqllogic Tests with Standalone mode with embedded meta-store
      shell: bash
      env:
        TEST_HANDLERS: ${{ inputs.handlers }}
      run: |
        bash ./scripts/ci/ci-run-sqllogic-tests.sh ${{ inputs.dirs }}

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-sqllogic-standalone-macos-${{ inputs.handlers }}-${{ inputs.dirs }}
