[package]
name = "databend-storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
dev = ["snap"]

[dependencies]

databend-common-base = { workspace = true }
databend-common-datavalues = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-io = { workspace = true }
databend-common-native = { workspace = true }
databend-common-storage = { workspace = true }

bincode_v1 = { workspace = true }
chrono = { workspace = true }
enum-as-inner = { workspace = true }
log = { workspace = true }
parquet = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
simple_hll = { workspace = true, features = ["serde_borsh"] }
snap = { workspace = true, optional = true }
typetag = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true
