name: "Test Fuzz Standalone"
description: "Running fuzz tests in standalone mode"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test

    - name: Test setup
      shell: bash
      run: |
        bash ./scripts/setup/dev_setup.sh -yd

    - name: Run fuzz Tests with Standalone mode with embedded meta-store
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-fuzz-tests.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-fuzz-standalone-linux
