apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: single
servers: 1
image: rancher/k3s:v1.29.5-k3s1
ports:
  - port: 8888:80
    nodeFilters:
      - loadbalancer
registries:
  use:
    - k3d-registry.localhost:5111
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  k3s:
    nodeLabels:
      - label: node.datafuselabs.io/role=warehouse
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
