---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meta-service-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/databend/meta"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meta-service
  labels:
    app: meta-service
spec:
  serviceName: "meta-service"
  replicas: 1
  selector:
    matchLabels:
      app: meta-service
  template:
    metadata:
      labels:
        app: meta-service
    spec:
      dnsConfig:
        searches:
          - "meta-service.databend-system.svc.cluster.local"
      containers:
        - name: databend-meta
          image: datafuselabs/databend-meta:latest
          command:
            - /databend-meta
          args:
            - --single
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_NAME
              value: "meta-service"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: METASRV_LOG_DIR
              value: /mnt/data/log
            - name: KVSRV_RAFT_DIR
              value: /mnt/data/raft
            - name: ADMIN_API_ADDRESS
              value: "$(POD_IP):28002"
            - name: METASRV_GRPC_API_ADDRESS
              value: "$(POD_IP):9191"
            - name: KVSRV_API_PORT
              value: "28004"
            - name: KVSRV_LISTEN_HOST
              value: "$(POD_IP)"
            - name: KVSRV_ADVERTISE_HOST
              value: "$(POD_NAME).$(POD_SERVICE_NAME).$(POD_NAMESPACE)"
            - name: KVSRV_ID
              value: "1"
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 28002
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          ports:
            - name: metrics
              containerPort: 28001
            - name: admin
              containerPort: 28002
            - name: flight
              containerPort: 9191
            - name: raft
              containerPort: 28004
          volumeMounts:
            - name: data
              mountPath: /mnt/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-storage
        volumeName: meta-service-pv-volume
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: meta-service
  labels:
    app: meta-service
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 28001
      targetPort: 28001
    - name: admin
      port: 28002
      targetPort: 28002
    - name: flight
      port: 9191
      targetPort: 9191
    - name: raft
      port: 28004
      targetPort: 28004
  selector:
    app: meta-service
