name: "Setup BendSQL"
description: "Setup BendSQL for CI"
runs:
  using: "composite"
  steps:
    - name: Install for Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if command -v bendsql >/dev/null 2>&1; then
          bendsql --version
          exit 0
        fi
        case $RUNNER_PROVIDER in
          aws)
            aws s3 cp s3://databend-ci/packages/bendsql_$(dpkg --print-architecture).deb /tmp/bendsql.deb --no-progress
            sudo dpkg -i /tmp/bendsql.deb
            ;;
          gcp)
            gsutil cp gs://databend-ci/packages/bendsql_$(dpkg --print-architecture).deb /tmp/bendsql.deb --no-progress
            sudo dpkg -i /tmp/bendsql.deb
            ;;
          *)
            curl -fsSL https://repo.databend.com/install/bendsql.sh | bash -s -- -y --prefix /usr/local
            ;;
        esac
        bendsql --version

    - name: Install for macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        if command -v bendsql >/dev/null 2>&1; then
          bendsql --version
          exit 0
        fi
        brew install databendcloud/homebrew-tap/bendsql
        bendsql --version
