name: "Download Artifacts"
description: "Download build Result Binaries"
inputs:
  sha:
    description: "git sha"
    required: true
  target:
    description: ""
    required: true
  category:
    description: "default/hdfs/udf"
    required: false
    default: default
  path:
    description: "default to ./target/${BUILD_PROFILE}/"
    required: false
    default: ""
  artifacts:
    description: "Artifacts to download, only works with s3/gcs"
    required: false
    default: "meta,query"
outputs:
  path:
    description: ""
    value: ${{ steps.info.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: Check Disk Space
      shell: bash
      run: |
        df -h

    - name: Get Download Info
      id: info
      shell: bash
      run: |
        if [[ -z "${{ inputs.path }}" ]]; then
          path="./target/${{ env.BUILD_PROFILE }}"
        else
          path="${{ inputs.path }}"
        fi
        echo "path=${path}" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@v4
      if: env.RUNNER_PROVIDER == 'github'
      with:
        name: ${{ env.BUILD_PROFILE }}-${{ inputs.sha }}-${{ inputs.target }}-${{ inputs.category }}
        path: ${{ steps.info.outputs.path }}/

    - name: Make Executable
      if: env.RUNNER_PROVIDER == 'github'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          chmod +x ${{ steps.info.outputs.path }}/databend-$artifact
        done

    - name: Download artifact from s3
      if: env.RUNNER_PROVIDER == 'aws'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          echo "==> fetching databend-$artifact ..."
          aws s3 cp s3://databend-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/databend-$artifact ${{ steps.info.outputs.path }}/databend-$artifact --no-progress
          chmod +x ${{ steps.info.outputs.path }}/databend-$artifact
        done

    - name: Download artifact from gcs
      if: env.RUNNER_PROVIDER == 'gcp'
      shell: bash
      run: |
        gcloud config set storage/parallel_composite_upload_enabled False
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          echo "==> fetching databend-$artifact ..."
          gcloud storage cp gs://databend-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/databend-$artifact ${{ steps.info.outputs.path }}/databend-$artifact
          chmod +x ${{ steps.info.outputs.path }}/databend-$artifact
        done

    - name: Check Disk Space
      shell: bash
      run: |
        df -h
