name: "Test Stateful Standalone Iceberg Rest"
description: "Running Stateful Iceberg Rest tests in standalone mode"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test

    - name: Iceberg Rest Setup for (ubuntu-latest only)
      shell: bash
      run: |
        docker-compose -f "./docker/it-iceberg-rest/docker-compose.yaml" up --quiet-pull -d

    - name: Run Stateful Tests with Standalone mode
      shell: bash
      run: |
        ./scripts/ci/ci-run-stateful-iceberg-rest-tests-standalone.sh
