# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
shutdown_wait_timeout_ms = 5000

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8081"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7071"

# For flight rpc.
flight_api_address = "0.0.0.0:9091"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8124

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8000

# In mgr mode, we also need to config the tenant_id, such as system.
tenant_id = "system"
cluster_id = "system_mgr_1"
# Management mode enable.
management_mode = true

[[query.users]]
name = "root"
auth_type = "no_password"

[[query.users]]
name = "default"
auth_type = "no_password"

[log]

[log.file]
level = "DEBUG"
format = "text"
dir = "./.databend/logs_management_mode"

[meta]
# To enable embedded meta-store, set address to ""
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60

# Storage config.
[storage]
# fs|s3
type = "fs"

# FS storage.
[storage.fs]
data_path = "management_data"
