name: macOS

on:
  workflow_call:
    inputs:
      build_profile:
        description: 'Build profile, debug or release'
        type: string
        required: true
        default: 'debug'

env:
  BUILD_PROFILE: ${{ inputs.build_profile }}
  RUNNER_PROVIDER: github

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_macos
        with:
          target: ${{ matrix.arch }}-apple-darwin

  test_stateless_standalone:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateless_standalone_macos

  test_stateless_cluster:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_stateless_cluster_macos
        timeout-minutes: 30

  sqllogic_standalone:
    runs-on: macos-latest
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_sqllogic_standalone_macos
        timeout-minutes: 20
        with:
          dirs: ${{ matrix.dirs }}
